//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.16 at 02:05:45 PM MSK 
//


package ru.stc5.niksergey.models.xjc;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.stc5.niksergey.models.xjc package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CarModel_QNAME = new QName("", "CarModel");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.stc5.niksergey.models.xjc
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CarModelType }
     * 
     */
    public CarModelType createCarModelType() {
        return new CarModelType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CarModelType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CarModel")
    public JAXBElement<CarModelType> createCarModel(CarModelType value) {
        return new JAXBElement<CarModelType>(_CarModel_QNAME, CarModelType.class, null, value);
    }

}
