//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.17 at 03:09:03 PM MSK 
//


package ru.stc5.niksergey.models.xjc;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.stc5.niksergey.models.xjc package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Car_QNAME = new QName("", "Car");
    private final static QName _CarModel_QNAME = new QName("", "CarModel");
    private final static QName _Leaser_QNAME = new QName("", "Leaser");
    private final static QName _Rent_QNAME = new QName("", "Rent");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.stc5.niksergey.models.xjc
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Car }
     * 
     */
    public Car createCar() {
        return new Car();
    }

    /**
     * Create an instance of {@link CarModel }
     * 
     */
    public CarModel createCarModel() {
        return new CarModel();
    }

    /**
     * Create an instance of {@link Leaser }
     * 
     */
    public Leaser createLeaser() {
        return new Leaser();
    }

    /**
     * Create an instance of {@link Rent }
     * 
     */
    public Rent createRent() {
        return new Rent();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Car }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Car")
    public JAXBElement<Car> createCar(Car value) {
        return new JAXBElement<Car>(_Car_QNAME, Car.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CarModel }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CarModel")
    public JAXBElement<CarModel> createCarModel(CarModel value) {
        return new JAXBElement<CarModel>(_CarModel_QNAME, CarModel.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Leaser }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Leaser")
    public JAXBElement<Leaser> createLeaser(Leaser value) {
        return new JAXBElement<Leaser>(_Leaser_QNAME, Leaser.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Rent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Rent")
    public JAXBElement<Rent> createRent(Rent value) {
        return new JAXBElement<Rent>(_Rent_QNAME, Rent.class, null, value);
    }

}
